## TODO: Currently, Halo does not support i18n for configuration file descriptions
## So Simplified Chinese is temporarily used as the default description language.

apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: additional-webfilter
spec:
  className: run.halo.app.security.AdditionalWebFilter
  displayName: "Additional Web Filter"
  type: MULTI_INSTANCE
  description: "Chain processing for web requests, used for cross-cutting concerns such as security and timeouts."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-post-content-handler
spec:
  className: run.halo.app.theme.ReactivePostContentHandler
  displayName: "Post Content Handler"
  type: MULTI_INSTANCE
  description: "Extends post content displayed on the theme side."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-singlepage-content-handler
spec:
  className: run.halo.app.theme.ReactiveSinglePageContentHandler
  displayName: "Page Content Handler"
  type: MULTI_INSTANCE
  description: "Extends page content displayed on the theme side."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: comment-widget
spec:
  className: run.halo.app.theme.dialect.CommentWidget
  displayName: "Comment Widget"
  type: SINGLETON
  description: "Extends the comment component displayed on post pages."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: username-password-authentication-manager
spec:
  className: run.halo.app.security.authentication.login.UsernamePasswordAuthenticationManager
  displayName: "Username/Password Authentication Manager"
  type: SINGLETON
  description: "Extends username/password authentication."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-notifier
spec:
  className: run.halo.app.notification.ReactiveNotifier
  displayName: "Notification Notifier"
  type: MULTI_INSTANCE
  description: "Extends notification notifiers to send notifications to users."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: search-engine
spec:
  className: run.halo.app.search.SearchEngine
  displayName: "Search Engine"
  type: SINGLETON
  description: "Extends content search engine."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: template-footer-processor
spec:
  className: run.halo.app.theme.dialect.TemplateFooterProcessor
  displayName: Footer Content Processor
  type: MULTI_INSTANCE
  description: "Provides extension points for &lt;halo:footer/&gt; tag content."
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: excerpt-generator
spec:
  className: run.halo.app.content.ExcerptGenerator
  displayName: Excerpt Generator
  type: SINGLETON
  description: "Provides extension points for auto-generating excerpts, such as using algorithms or AI generation."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: thumbnail-provider
spec:
  className: run.halo.app.core.attachment.ThumbnailProvider
  displayName: Image Thumbnail Generation
  type: MULTI_INSTANCE
  description: "Provides extension points for generating image thumbnails."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: attachment-handler
spec:
  className: run.halo.app.core.extension.attachment.endpoint.AttachmentHandler
  displayName: "Attachment Storage Policy"
  type: MULTI_INSTANCE
  description: "Provides extension points for attachment upload, deletion, and storage."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: comment-subject
spec:
  className: run.halo.app.content.comment.CommentSubject
  displayName: "Comment Subject"
  type: MULTI_INSTANCE
  description: "Provides extension points for displaying comment subjects."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: template-head-processor
spec:
  className: run.halo.app.theme.dialect.TemplateHeadProcessor
  displayName: "Head Content Processor"
  type: MULTI_INSTANCE
  description: "Provides extension points for customizing &lt;head&gt; tag content in theme pages."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: element-tag-post-processor
spec:
  className: run.halo.app.theme.dialect.ElementTagPostProcessor
  displayName: "Element Tag Post Processor"
  type: MULTI_INSTANCE
  description: "Provides extension points for post-processing Thymeleaf element tags."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: before-security-webfilter
spec:
  className: run.halo.app.security.BeforeSecurityWebFilter
  displayName: "Security Pre Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for web filters executed at the front of the security filter chain."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: after-security-webfilter
spec:
  className: run.halo.app.security.AfterSecurityWebFilter
  displayName: "Security Post Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for web filters executed at the end of the security filter chain."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: http-basic-security-webfilter
spec:
  className: run.halo.app.security.HttpBasicSecurityWebFilter
  displayName: "HTTP Basic Auth Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for HTTP Basic authentication logic."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: form-login-security-webfilter
spec:
  className: run.halo.app.security.FormLoginSecurityWebFilter
  displayName: "Form Login Auth Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for form login authentication logic."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: authentication-security-webfilter
spec:
  className: run.halo.app.security.AuthenticationSecurityWebFilter
  displayName: "General Auth Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for general authentication logic."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: anonymous-authentication-security-webfilter
spec:
  className: run.halo.app.security.AnonymousAuthenticationSecurityWebFilter
  displayName: "Anonymous Auth Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for anonymous authentication logic."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: oauth2-authorization-code-security-webfilter
spec:
  className: run.halo.app.security.OAuth2AuthorizationCodeSecurityWebFilter
  displayName: "OAuth2 Authorization Code Filter"
  type: MULTI_INSTANCE
  description: "Provides extension points for OAuth2 authorization code authentication logic."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: halo-documents-provider
spec:
  className: run.halo.app.search.HaloDocumentsProvider
  displayName: "Search Document Provider"
  type: MULTI_INSTANCE
  description: "Provides document data for rebuilding search indexes."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: user-pre-creating-handler
spec:
  className: run.halo.app.core.user.service.UserPreCreatingHandler
  displayName: "User Pre-Creation Handler"
  type: MULTI_INSTANCE
  description: "Provides extension points for executing custom logic before user creation."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: user-post-creating-handler
spec:
  className: run.halo.app.core.user.service.UserPostCreatingHandler
  displayName: "User Post-Creation Handler"
  type: MULTI_INSTANCE
  description: "Provides extension points for executing custom logic after user creation."
