apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-anon-setting
spec:
  forms:
    - group: layout
      label: Layout
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: Posts Layout
          value: grid_3
          options:
            - label: Grid (3 columns)
              value: grid_3
            - label: Grid (2 columns)
              value: grid_2
            - label: Single
              value: single
          help: "When set to Single, post card images will be positioned on the left."
        - $formkit: select
          name: header_widget
          id: header_widget
          label: Header Widget
          value: latest_post
          options:
            - label: None
              value: none
            - label: Latest Post
              value: latest_post
            - label: Post Grid (Latest 5 Posts)
              value: latest_post_grid
            - label: Site Title
              value: site_title
        - $formkit: select
          if: "$get(header_widget).value !== none"
          name: header_background_type
          id: header_background_type
          key: header_background_type
          label: Header Background
          value: image
          options:
            - label: Manual
              value: manual
            - label: Image
              value: image
        - $formkit: text
          if: "$get(header_widget).value !== none && $get(header_background_type).value === manual"
          name: header_background
          label: Header Background
        - $formkit: attachment
          if: "$get(header_widget).value !== none && $get(header_background_type).value === image"
          name: header_background_image
          label: Header Background Image
    - group: style
      label: Style
      formSchema:
        - $formkit: select
          name: color_scheme
          label: Default Color Scheme
          value: system
          options:
            - label: Follow System
              value: system
            - label: Dark
              value: dark
            - label: Light
              value: light
        - $formkit: checkbox
          name: enable_change_color_scheme
          label: Allow Visitors to Toggle Color Scheme
          value: true
        - $formkit: checkbox
          name: show_scroll_button
          label: Show Scroll-to-Top Button
          value: true
    - group: post
      label: Posts
      formSchema:
        - $formkit: select
          name: content_style
          label: Content Style
          value: "github"
          options:
            - label: GitHub Style
              value: github
            - label: Tailwind CSS Typography
              value: tailwind
        - $formkit: select
          name: title_position
          label: Title Position
          value: "content"
          options:
            - value: "content"
              label: "In Content"
            - value: "cover"
              label: "In Cover"
        - $formkit: text
          name: cover_height
          label: Cover Image Height
          value: "24rem"
        - $formkit: checkbox
          name: show_upvote_button
          label: Show Upvote Button
          value: true
        - $formkit: checkbox
          name: show_share_button
          label: Show Share Button
          value: true
    - group: sidebar
      label: Sidebar
      formSchema:
        - $formkit: array
          name: widgets
          label: Widgets
          value:
            - value: popular-posts
            - value: categories
            - value: tags
          itemLabels:
            - type: "text"
              label: "$value.value"
          children:
            - $formkit: select
              name: value
              label: Widget
              options:
                - label: Profile
                  value: profile
                - label: Popular Posts
                  value: popular-posts
                - label: Categories
                  value: categories
                - label: Tags
                  value: tags
    - group: footer
      label: Footer
      formSchema:
        - $formkit: select
          name: style
          label: Footer Style
          value: style_1
          options:
            - label: Style 1
              value: style_1
        - $formkit: text
          name: slogan
          label: Slogan
        - $formkit: array
          name: social_media
          label: Social Media
          value: []
          itemLabels:
            - type: "text"
              label: "$value.name"
          children:
            - $formkit: select
              name: icon
              label: Icon
              options:
                - label: GitHub
                  value: i-simple-icons-github
                - label: Twitter
                  value: i-simple-icons-twitter
                - label: Telegram
                  value: i-simple-icons-telegram
                - label: RSS
                  value: i-simple-icons-rss
                - label: Email
                  value: i-tabler-mail
            - $formkit: text
              name: name
              label: Name
            - $formkit: text
              name: url
              label: URL
              validation: "required"
    - group: beian
      label: Legal
      formSchema:
        - $formkit: text
          name: icp_text
          label: ICP Filing Number
        - $formkit: text
          name: icp_link
          label: ICP Filing Link
          value: https://beian.miit.gov.cn/
