# Initial data for fresh Halo installations
apiVersion: content.halo.run/v1alpha1
kind: Category
metadata:
  name: 76514a40-6ef1-4ed9-b58a-e26945bde3ca
spec:
  displayName: Default Category
  slug: default
  description: This is your default category. Delete it if not needed.
  cover: ""
  template: ""
  priority: 0
  children: []
status:
  permalink: "/categories/default"

---
apiVersion: content.halo.run/v1alpha1
kind: Tag
metadata:
  name: c33ceabb-d8f1-4711-8991-bb8f5c92ad7c
spec:
  displayName: Halo
  slug: halo
  cover: ""
status:
  permalink: "/tags/halo"

---
# Post content snapshot
apiVersion: content.halo.run/v1alpha1
kind: Snapshot
metadata:
  name: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  annotations:
    content.halo.run/keep-raw: "true"
spec:
  subjectRef:
    group: content.halo.run
    version: v1alpha1
    kind: Post
    name: 5152aea5-c2e8-4717-8bba-2263d46e19d5
  rawType: HTML
  rawPatch: <h2 id="hello-halo"><strong>Hello
    Halo</strong></h2><p>If you are seeing this post, it means you have successfully
    installed Halo. Thank you for using <a target="_blank"
    rel="noopener noreferrer nofollow" href="https://www.halo.run/">Halo</a>
    and we hope you enjoy creating with it.</p><h2
    id="links"><strong>Links</strong></h2><ul><li><p>Website: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run">https://www.halo.run</a></p></li><li><p>Docs: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://docs.halo.run">https://docs.halo.run</a></p></li><li><p>Community: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://bbs.halo.run">https://bbs.halo.run</a></p></li><li><p>App Market: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run/store/apps">https://www.halo.run/store/apps</a></p></li><li><p>Source Code: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://github.com/halo-dev/halo">https://github.com/halo-dev/halo</a></p></li></ul><p>If you have any questions while using Halo, you can find answers through the links above or contact us.</p><blockquote><p>This is an automatically generated post. Please delete it and start creating!</p></blockquote>
  contentPatch: <h2 id="hello-halo"><strong>Hello
    Halo</strong></h2><p>If you are seeing this post, it means you have successfully
    installed Halo. Thank you for using <a target="_blank"
    rel="noopener noreferrer nofollow" href="https://www.halo.run/">Halo</a>
    and we hope you enjoy creating with it.</p><h2
    id="links"><strong>Links</strong></h2><ul><li><p>Website: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run">https://www.halo.run</a></p></li><li><p>Docs: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://docs.halo.run">https://docs.halo.run</a></p></li><li><p>Community: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://bbs.halo.run">https://bbs.halo.run</a></p></li><li><p>App Market: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run/store/apps">https://www.halo.run/store/apps</a></p></li><li><p>Source Code: <a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://github.com/halo-dev/halo">https://github.com/halo-dev/halo</a></p></li></ul><p>If you have any questions while using Halo, you can find answers through the links above or contact us.</p><blockquote><p>This is an automatically generated post. Please delete it and start creating!</p></blockquote>
  lastModifyTime: "${timestamp}"
  owner: "${username}"
  contributors:
    - "${username}"

---
# Initial post
apiVersion: content.halo.run/v1alpha1
kind: Post
metadata:
  name: 5152aea5-c2e8-4717-8bba-2263d46e19d5
spec:
  title: Hello Halo
  slug: hello-halo
  releaseSnapshot: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  headSnapshot: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  baseSnapshot: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  owner: "${username}"
  template: ""
  cover: ""
  deleted: false
  publish: true
  publishTime: "${timestamp}"
  pinned: false
  allowComment: true
  visible: PUBLIC
  priority: 0
  excerpt:
    autoGenerate: false
    raw: If you are seeing this post, it means you have successfully installed Halo. Thank you for using Halo and we hope you enjoy creating with it.
  categories:
    - 76514a40-6ef1-4ed9-b58a-e26945bde3ca
  tags:
    - c33ceabb-d8f1-4711-8991-bb8f5c92ad7c
  htmlMetas: []
status:
  permalink: /archives/hello-halo

---
# Custom page content snapshot
apiVersion: content.halo.run/v1alpha1
kind: Snapshot
metadata:
  name: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  annotations:
    content.halo.run/keep-raw: "true"
spec:
  subjectRef:
    group: content.halo.run
    version: v1alpha1
    kind: SinglePage
    name: 373a5f79-f44f-441a-9df1-85a4f553ece8
  rawType: HTML
  rawPatch:
    <h2><strong>About Page</strong></h2><p>This is a custom page. You can find it in the admin console under <code>Pages</code>
    -&gt; <code>Custom Pages</code>. Use it to create an About page, Contact Us page, etc.</p><blockquote><p>This is an auto-generated page. You can delete it from the admin console.</p></blockquote>
  contentPatch:
    <h2><strong>About Page</strong></h2><p>This is a custom page. You can find it in the admin console under <code>Pages</code>
    -&gt; <code>Custom Pages</code>. Use it to create an About page, Contact Us page, etc.</p><blockquote><p>This is an auto-generated page. You can delete it from the admin console.</p></blockquote>
  lastModifyTime: "${timestamp}"
  owner: "${username}"
  contributors:
    - "${username}"

---
# Initial custom page
apiVersion: content.halo.run/v1alpha1
kind: SinglePage
metadata:
  name: 373a5f79-f44f-441a-9df1-85a4f553ece8
spec:
  title: About
  slug: about
  template: ""
  cover: ""
  owner: "${username}"
  deleted: false
  publish: true
  baseSnapshot: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  headSnapshot: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  releaseSnapshot: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  pinned: false
  allowComment: true
  visible: PUBLIC
  version: 1
  priority: 0
  excerpt:
    autoGenerate: false
    raw: This is a custom page. You can find it in the admin console under Pages -> Custom Pages. Use it to create an About page, Contact Us page, etc.
  htmlMetas: []
status:
  permalink: "/about"

---
# Homepage menu item
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: 88c3f10b-321c-4092-86a8-70db00251b74
spec:
  displayName: Home
  href: /
  children: []
  priority: 0
---
# Link to post as menu
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: c4c814d1-0c2c-456b-8c96-4864965fee94
spec:
  displayName: "Hello Halo"
  href: "/archives/hello-halo"
  children: []
  priority: 1
  targetRef:
    group: content.halo.run
    version: v1alpha1
    kind: Post
    name: 5152aea5-c2e8-4717-8bba-2263d46e19d5
---
# Link to tag as menu
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: 35869bd3-33b5-448b-91ee-cf6517a59644
spec:
  displayName: "Halo"
  href: "/tags/halo"
  children: []
  priority: 2
  targetRef:
    group: content.halo.run
    version: v1alpha1
    kind: Tag
    name: c33ceabb-d8f1-4711-8991-bb8f5c92ad7c
---
# Link to custom page as menu
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: b0d041fa-dc99-48f6-a193-8604003379cf
spec:
  displayName: "About"
  href: "/about"
  children: []
  priority: 3
  targetRef:
    group: content.halo.run
    version: v1alpha1
    kind: SinglePage
    name: 373a5f79-f44f-441a-9df1-85a4f553ece8
---
apiVersion: v1alpha1
kind: Menu
metadata:
  name: primary
spec:
  displayName: Main Menu
  menuItems:
    - 88c3f10b-321c-4092-86a8-70db00251b74
    - c4c814d1-0c2c-456b-8c96-4864965fee94
    - 35869bd3-33b5-448b-91ee-cf6517a59644
    - b0d041fa-dc99-48f6-a193-8604003379cf
